name: Update Scotland Forecast

on:
  schedule:
    - cron: "30 6 * * *"   # Every day at 06:30 UTC (09:30 TR)
  workflow_dispatch:       # Manual trigger option

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run forecast update
        run: |
          TODAY=$(date -u +%Y%m%d)
          echo "Downloading GFS for $TODAY 01Z..."
          wget https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.${TODAY}/01/atmos/gfs.t01z.pgrb2.0p25.f000 -O gfs.t01z.f000
          # Burada kendi forecast scriptini çalıştırıyorsun, örn:
          # python scripts/update_forecast.py

      - name: Create metadata
        run: |
          TODAY=$(date -u +%Y%m%d)
          UTC_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
          TR_TIME=$(date -d "$UTC_TIME +3 hours" +"%Y-%m-%d %H:%M GMT+3")
          
          echo "{
            \"last_update\": \"$UTC_TIME\",
            \"last_update_tr\": \"$TR_TIME\",
            \"cron_time\": \"06:30 UTC / 09:30 GMT+3\",
            \"note\": \"Forecasts are updated daily at 06:30 UTC (09:30 GMT+3). GFS data becomes available ~3–4 hours after model run time.\"
          }" > metadata.json

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add metadata.json
          git commit -m "Update forecast metadata $UTC_TIME"
          git push
