name: Update Forecast

on:
  workflow_dispatch:

permissions:
  contents: write  # Repo'ya push izni

jobs:
  update_forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xarray cfgrib requests

      - name: Download latest GFS GRIB
        run: |
          mkdir -p data
          curl -o data/gfs_latest.grib "https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.$(date -u +%Y%m%d)/00/atmos/gfs.t00z.pgrb2.0p25.f000"

      - name: Generate forecast
        run: |
          python generate_forecast.py

      - name: Commit updated forecast
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add forecast_output.csv  # forecast dosyanın adı neyse onu yaz
          git commit -m "Update forecast [skip ci]" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main

