name: UK Renewables Forecast

# Manuel tetikleme için
on:
  workflow_dispatch:

jobs:
  generate_forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gereken paketleri kur
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas xarray cfgrib requests

      - name: Forecast ve Price/Volume oluştur
        run: |
          python generate_forecast.py

      - name: Oluşan JSON dosyalarını kontrol et
        run: |
          ls -lh data/
