name: Update Scotland Forecast JSON

on:
  schedule:
    - cron: '0 0 * * *'   # Her gün UTC 00:00
  workflow_dispatch:       # Manuel çalıştırma

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install xarray cfgrib numpy

    - name: Download latest GFS 0.25° GRIB
      run: |
        TODAY=$(date -u +%Y%m%d)
        HOUR=$(date -u +%H)
        wget -O gfs.grib "https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.${TODAY}/${HOUR}/atmos/gfs.t${HOUR}z.pgrb2.0p25.f000"

    - name: Generate JSON
      run: python generate_forecast.py

    - name: Commit & Push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add data/scotland_forecast.json
        git commit -m "Update Scotland forecast JSON [skip ci]" || echo "No changes to commit"
        git push
