name: Update Forecast

on:
  workflow_dispatch:

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xarray cfgrib requests pandas

      - name: Download latest GFS GRIB file
        run: |
          mkdir -p data
          cd data
          # Güncel tarih ve saat için dosya URL'si
          TODAY=$(date -u +%Y%m%d)
          HOUR=18  # 00, 06, 12, 18 seçeneklerinden biri
          URL="https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.${TODAY}/${HOUR}/atmos/gfs.t${HOUR}z.pgrb2.0p25.f000"
          echo "Downloading $URL"
          wget -O gfs_latest.grib $URL

      - name: Run forecast script
        run: |
          python generate_forecast.py

      - name: Commit forecast if CSV exists
        if: success() && always() && (steps.run-forecast.outputs.file-exists == 'true' || true)
        run: |
          if [ -f "forecast_output.csv" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add forecast_output.csv
            git commit -m "Update forecast output"
            git push
          else
            echo "forecast_output.csv not found, skipping commit."
          fi
