name: Update Scotland Forecast

on:
  schedule:
    # Her gün Türkiye saati 13:30'da (UTC 10:30)
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install xarray cfgrib requests pandas matplotlib

      - name: Run forecast script
        run: python generate_forecast.py

      - name: Commit forecast output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add forecast_output.csv
          git commit -m "Update forecast data"
          git push
