name: Update Scotland Forecast

on:
  schedule:
    - cron: "30 6 * * *"   # Every day at 06:30 UTC (09:30 TR)
  workflow_dispatch:       # Manual trigger option

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run forecast update
        run: |
          TODAY=$(date -u +%Y%m%d)
          echo "Downloading GFS for $TODAY 01Z..."
          wget https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.${TODAY}/01/atmos/gfs.t01z.pgrb2.0p25.f000 -O gfs.t01z.f000

      - name: Commit and push results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update forecast for $TODAY"
          git push
