name: Update Forecast

on:
  workflow_dispatch:  # Manuel veya API ile tetikleme

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas numpy xarray cfgrib

      - name: Run forecast script
        run: python generate_forecast.py

      - name: Commit JSON updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update forecast data"
          git push
